version: 2.0

CODECOV_TOKEN="f1b7eb21-d3cf-4228-a19c-9aaed7923908"

jobs:
    build:
        docker:
            - image: circleci/openjdk:9-jdk-sid-node-browsers
        steps:
            - checkout
            - restore_cache:
                keys:
                    - gradle-{{ checksum "build.gradle" }}
            - run: gradle assemble
            - run: gradle test
            - save_cache:
                paths:
                    - ~/.gradle
                key: gradle-{{ checksum "build.gradle" }}
            - store_artifacts:
                path: build/distributions
                destination: distributions
            - store_artifacts:
                path: build/libs
destination: libs

general:
    artifacts:
        - "build/reports/jacoco"

test:
    post:
        - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
        - bash <(curl -s https://codecov.io/bash)
